"""create videojuegos tables

Revision ID: d638b03bdf1e
Revises: 
Create Date: 2026-03-07 22:48:04.287758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd638b03bdf1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('juegos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_lanzamiento', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('generos', sa.String(length=255), nullable=True),
    sa.Column('plataformas', sa.String(length=255), nullable=True),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_juego_rating', 'juegos', ['rating'], unique=False)
    op.create_index(op.f('ix_juegos_fecha_extraccion'), 'juegos', ['fecha_extraccion'], unique=False)
    op.create_index(op.f('ix_juegos_igdb_id'), 'juegos', ['igdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_juegos_igdb_id'), table_name='juegos')
    op.drop_index(op.f('ix_juegos_fecha_extraccion'), table_name='juegos')
    op.drop_index('idx_juego_rating', table_name='juegos')
    op.drop_table('juegos')
    # ### end Alembic commands ###
